# Projeto NodeJS Handling Errors üöß
Projeto em NodeJS a fim de tratar erros. Entender e categorizar os diferentes tipos de erros ajuda a lidar eficientemente com problemas que possam surgir durante a execu√ß√£o do sistema. Principais t√≥picos abordados durante o desenvolvimento:

---

# Tipos de erros:

### 1. Erros T√©cnicos/De Rede üåê
Esses s√£o erros relacionados a quest√µes t√©cnicas ou de rede que podem ocorrer durante a opera√ß√£o do sistema. Por exemplo, se o servidor MongoDB estiver inativo devido a um problema t√©cnico ou se houver uma falha de conex√£o de rede; 
- Servidor MongoDB cai;
- Exibe p√°gina de erro para o usu√°rio;

---

### 2. Erros "Esperados" ‚ö†Ô∏è
Esses erros s√£o previs√≠veis e geralmente ocorrem devido a situa√ß√µes espec√≠ficas, como a incapacidade de ler um arquivo ou uma falha na execu√ß√£o de uma opera√ß√£o no banco de dados. Eles s√£o chamados de "esperados" porque o sistema pode antecipar esses cen√°rios.
- Exemplo: N√£o √© poss√≠vel ler o arquivo, falha na opera√ß√£o do banco de dados;
- Informar o usu√°rio, possivelmente tentar novamente;

---

### 3. Bugs/Erros L√≥gicos" üêû
Esses s√£o erros relacionados a falhas no c√≥digo-fonte, onde ocorre um comportamento inesperado. Por exemplo, utilizar um objeto de usu√°rio que n√£o foi corretamente inicializado ou n√£o existe.
- Exemplo: Objeto do usu√°rio utilizado quando n√£o existe;
- Corrigir durante o desenvolvimento;

---

# Lidando com erros üöß

## 1. Quando o erro √© lan√ßado üí•
**C√≥digo S√≠ncrono (try catch) üîÑ**
- Quando voc√™ est√° lidando com c√≥digo s√≠ncrono, o uso do bloco try catch √© uma pr√°tica comum. Isso permite que voc√™ envolva se√ß√µes de c√≥digo onde erros podem ocorrer no bloco try e capture esses erros no bloco catch. Isso proporciona controle sobre como os erros s√£o tratados, permitindo a execu√ß√£o de a√ß√µes espec√≠ficas quando uma exce√ß√£o √© detectada;

**C√≥digo Ass√≠ncrono (then() catch()) ‚è≥**
- Em opera√ß√µes ass√≠ncronas, como Promises, √© comum utilizar then() e catch() para lidar com sucessos e erros, respectivamente. O bloco catch √© executado quando ocorre um erro durante a execu√ß√£o da Promise;

**Lidar Diretamente com o Erro üö®**
- Em algumas situa√ß√µes, voc√™ pode optar por lidar diretamente com o erro no ponto em que ele ocorre, sem utilizar constru√ß√µes como try catch ou catch();

**Usar a Fun√ß√£o de Tratamento de Erros do Express üåê**
- No contexto do Express.js, voc√™ pode usar a fun√ß√£o de tratamento de erros integrada para centralizar o tratamento de erros em sua aplica√ß√£o. Isso √© feito utilizando um middleware especial que captura erros, permitindo que voc√™ forne√ßa respostas adequadas ao usu√°rio;

---

## 2. Quando nenhum erro √© lan√ßado ‚úÖ
**Valida√ß√£o de Valores e Lan√ßamento de Erro üîç**
- Se nenhum erro √© lan√ßado naturalmente no c√≥digo, √© poss√≠vel realizar valida√ß√µes explicitamente e, se necess√°rio, lan√ßar um erro manualmente usando a palavra-chave throw. Isso √© √∫til quando certas condi√ß√µes precisam ser atendidas antes de prosseguir;

---

## 3. Poss√≠veis Resultados de Cen√°rios üìä
**P√°gina de Erro (ex: P√°gina 500) üö©üî¥** 
- Se um erro n√£o for tratado e n√£o for capturado, √© comum exibir uma p√°gina de erro padr√£o, como uma p√°gina 500 (Internal Server Error), para informar ao usu√°rio que algo inesperado aconteceu.

**P√°gina/Resposta Planejada com Informa√ß√µes de Erro ou Redirecionamento üìùüîÑ**
- Em certos casos, √© prefer√≠vel planejar respostas espec√≠ficas para diferentes tipos de erros. Isso pode incluir exibir uma p√°gina com informa√ß√µes detalhadas sobre o erro ou redirecionar o usu√°rio para uma p√°gina espec√≠fica, dependendo do contexto e da natureza do erro.

---

*Trabalhar com erros envolve uma abordagem equilibrada entre capturar erros de forma adequada para manter a estabilidade do aplicativo e fornecer respostas informativas aos usu√°rios quando algo n√£o ocorre conforme o esperado. A escolha entre diferentes m√©todos de tratamento de erros depender√° das necessidades espec√≠ficas de cada situa√ß√£o e da arquitetura da aplica√ß√£o.*

---

## Lan√ßando erros no c√≥digo üö®
#### 1. Tratamento com Throw new Error üöß
- **Tratamento de Usu√°rio N√£o Encontrado:** √© adicionada uma verifica√ß√£o para o caso em que o usu√°rio n√£o √© encontrado no banco de dados. Se user for falsy (no caso de n√£o existir), uma mensagem informativa √© exibida no console e o middleware avan√ßa para o pr√≥ximo middleware usando `next()`.

- **Tratamento de Erros Gerais:** No bloco catch, ao inv√©s de apenas imprimir o erro no console `(console.log(err))`, agora √© lan√ßada uma exce√ß√£o `(throw new Error(err))`. Isso transforma o erro em uma exce√ß√£o, o que pode ser √∫til para rastreamento e identifica√ß√£o mais eficientes de erros n√£o tratados.

- **Chamada do Pr√≥ximo Middleware:** Independentemente de o usu√°rio existir ou n√£o, o c√≥digo utiliza `next()` para passar para o pr√≥ximo middleware. Isso garante que o fluxo de execu√ß√£o continue mesmo em casos de erros ou quando o usu√°rio n√£o √© encontrado.
~~~javascript
User.findById(req.session.user._id)
  .then(user => {
    if (!user) {
      console.log("user doesn't exist");
      return next();
    }
    req.user = user;
    next();
  })
  .catch(err => {
    throw new Error(err);
  });
~~~

---

#### 2. Retornando p√°ginas de erros üö©üìÑ
- Este trecho de c√≥digo exporta uma fun√ß√£o que renderiza a p√°gina de erro 500;
~~~javascript
exports.get500 = (req, res, next) => {
  res.status(500).render('500', {
    pageTitle: 'Error!',
    path: '/500',
    isAuthenticated: req.session.isLoggedIn
  });
};
~~~
- Dentro de um bloco catch, quando ocorre um erro, o c√≥digo redireciona o usu√°rio para a rota `'/500'`
~~~javascript
.catch(err => {
  res.redirect('/500');
});
~~~

*Essencialmente, quando ocorre um erro durante a execu√ß√£o do c√≥digo, ele redireciona o usu√°rio para a p√°gina de erro 500, proporcionando uma experi√™ncia mais amig√°vel em caso de falhas no servidor.*

---